### ISSUE TITLE
Do you still have the so file for 2.10 ?

### ISSUE THREAD

**Issue by zippy-zebu** [ankitkv/PidginPlugins#3]
Hi,

Do you still have the so file for 2.10 ? Can you upload here on github releases ?

Bcz this [link](http://nevitus.com/files/pidgin/2.10.7/unityinteg.so) now returns 404 Not found.

**Comment by ankitkv** [comment]
Hi, thanks for bringing this up. This updated link should work (replace "nevitus.com" with "ankitvani.com"): https://ankitvani.com/files/pidgin/2.10.7/unityinteg.so

Please note, however, that this repository is no longer maintained.

**Comment by khurshid-alam** [comment]
Ok. Thanks.
